export const searoute: string[] = [
  "Toot/Finish",

  "Startup/Pulls",
  "Startup/Make tunac",
  "Startup/Swim Sprints",
  "Startup/Tune Snapper",
  "Startup/Drink beer",
  "Startup/Summon Resort Pass",
  "Startup/Sell Gems",
  "Startup/Mayam Calendar",
  "Startup/TakerSpace",
  "Startup/Leprecondo",
  "Startup/Grab Rakes",
  "Startup/Grab Scepter Items",
  "Startup/Set SIT Course",
  "Startup/Guild Pants Unlock",
  "Startup/Garden",
  "Startup/Censer Purchases",
  "Startup/Prepare Band",
  "Startup/Get Sheriff Equipment",
  "Startup/Talk to Old Man",
  "Startup/Open Ski Set",
  "Startup/Shower",
  "Startup/2002",

  "Starting Buffs/Get Accordion",
  "Starting Buffs/April Buffs",
  "Starting Buffs/Non-April Buffs",
  "Starting Buffs/Zirconia Buffs",
  "Starting Buffs/Alliedradio Boon",
  "Starting Buffs/Softcore Lighthouse",

  "Shadow Realm/Open Shadow Realm",
  "Shadow Realm/Displaced Fish Shadow Realm",
  "Shadow Realm/Express Card",
  "Shadow Realm/Remaining Shadow Realm Fights",
  "Shadow Realm/Use Candy Map",

  "Cyber realm/First Cyber Adventure",
  "Cyber realm/Flood Zone",
  "Cyber realm/Finish Cyber Realm",
  "Cyber realm/NEP",

  "Octopus Garden/Quiet Brawl",
  "Octopus Garden/Pre Flyer",
  "Octopus Garden/Dynamite",
  "Octopus Garden/Blast Garden",
  "Octopus Garden/More Garden",
  "Octopus Garden/Unlucky Garden",
  "Octopus Garden/Use Wriggling Pellet",
  "Octopus Garden/Turn in Quest",
  "Octopus Garden/Do Wreck",
  "Octopus Garden/Talk to brothers",
  "Octopus Garden/Acquire shark jumper",

  "Pre-Item Run/Shadow Rift Buff",
  "Pre-Item Run/Kill Miner",
  "Pre-Item Run/Free Mining",
  "Pre-Item Run/Manual Mining",
  "Pre-Item Run/Dive Bar Noncombats",
  "Pre-Item Run/Outpost Unlock",
  "Pre-Item Run/Outpost Freerun",
  "Pre-Item Run/Generate Sausage Goblin Egg",
  "Pre-Item Run/Run Sausage Goblin Egg",
  "Pre-Item Run/Candelabra Egg",
  "Pre-Item Run/Finish First Hab",
  "Pre-Item Run/Peridot Squid",
  "Pre-Item Run/Finish farming squids with freekills",
  "Pre-Item Run/Finish farming squids without freekills",
  "Pre-Item Run/Use ink bladders",

  "Item Run/Collect Buffs",
  "Item Run/Buy scuba gear",
  "Item Run/Buy goggles",
  "Item Run/Outpost Refract",
  "Item Run/Banish 1",
  "Item Run/Banish 2",
  "Item Run/Banish 3",
  "Item Run/Get lockkey",
  "Item Run/Get stashbox",
  "Item Run/Stashbox Trailmap",
  "Item Run/Corral Refract",
  "Item Run/Spend sand dollars",
  "Item Run/Create Sea Clothes",
  "Item Run/Create scale-mail underwear",
  "Item Run/Dive Bar Peridot",
  "Item Run/Dive Bar Lassoing",
  "Item Run/Remaining Lassoing",
  "Item Run/Peridot Seahorse",
  "Item Run/First Banish",
  "Item Run/Find that seahorse",
  "Item Run/Buy Mer-kin gear",
  "Item Run/Elementary School Refract",
  "Item Run/Elementary School Wrapup",
  "Item Run/Mer-kin Scholar Prep",
  "Item Run/Mer-kin Scholar Refract",
  "Item Run/Learn more vocab",
  "Item Run/Learn scroll words",
  "Item Run/Learn healscroll words",

  "Scholar/Get Dreadscroll",
  "Scholar/Eat nigiri",
  "Scholar/Use knucklebone",
  "Scholar/Cast Deep Dark Visions",
  "Scholar/Kill YogUrt",
  "Scholar/Collect Emergency Dreadscroll Clues",
  "Scholar/Guess Dreadscroll",
  "Scholar/Get More Clues",
  "Scholar/Do Skate Park",
  "Scholar/Get Fishy",
  "Scholar/Finish Dive Bar",
  "Scholar/Scholar Abyss",
  "Scholar/Abyss Mom",
  "Scholar/Gymnasium",
  "Scholar/Anemone Mine Stalling",

  "Colosseum/Get gladiator outfit",
  "Colosseum/Fights",
  "Colosseum/Buff for hard fights",
  "Colosseum/Hard fights",
  "Colosseum/Shub",

  "Wrapup/Fish Banish",
  "Wrapup/Tricking",
  "Wrapup/Do Habs",
  "Wrapup/Get Pearls",

  "Final Steps/Nautical Seaceress",
  "Final Steps/Spend Sea Pennies",
];
